name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: backend        # Checkout repo into backend folder

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
        working-directory: backend

      - run: npm test
        working-directory: backend

  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: frontend       # Checkout repo into frontend folder

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
        working-directory: frontend

      - run: npm test
        working-directory: frontend
